import { useEffect ,useState} from "react";
import axios from 'axios'

const Home=()=>{
    const [pics,setPics]=useState({})
    useEffect(()=>{
        axios.get('http://localhost:5000/api/v1/posts').then((res)=>{
            setPics(res.data)
        })    
        .catch((err)=>{
            console.log(err)
        })
    },[])    
    return(
        <div className="mx-auto max-w-7xl">
            <div className="mt-4">
                <h1 className="text-4xl font-extrabold text-start text-gray-950">The Community Showcase</h1>
                <p className="mt-2 font-extralight text-start text-gray-400 text-sm">Browse through collection of images generated by Ai</p>
            </div>
            <div className='mt-10 flex flex-col'>
                <label className='text-2xl text-gray-600 font-medium'>Search Posts</label>
                <input className="border-2 rounded-md ring-gray-700 border-gray-200 px-4 py-2 w-7/12 text-stone-600 font-medium"/>
                <button className='p-2 w-24 italic rounded-md bg-gradient-to-r from-gray-400 to-gray-600 hover:from-gray-800 hover:to-gray-600 mt-4'>
                    Search
                </button>
            </div>
            
        </div>
    )
}
export default Home;